// Code generated by Kitex v0.7.3. DO NOT EDIT.
package searchsvr

import (
	server "github.com/cloudwego/kitex/server"
	search_svr "rpc_test/kitex_gen/search_svr"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler search_svr.SearchSvr, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
